version: '3'
services:  
    postgres:
        container_name: postgres_data
        image: postgres:9.6
        ports: 
            - 5432:5432
        volumes:
            - ../postgre_db/:/var/lib/postgresql/data
        env_file:
            - ./.env
        environment:
            POSTGRES_ROOT_PASSWORD: password
            POSTGRES_DB: test_db
            POSTGRES_PASSWORD: '12345'
            POSTGRES_PORT: '5432'